export enum ArticleBuilderWidgetType {
  SECTION = "SECTION",
  SUB_SECTION = "SUB_SECTION",
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  READING_TIME = "READING_TIME",
  CALL_TO_ACTION = "CALL_TO_ACTION",
  TABLE_OF_CONTENTS = "TABLE_OF_CONTENTS",
}
